name: AutoTriage (Issues)

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage_issue:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: AutoTriage - triage issue
        uses: danielchalmers/AutoTriage@main
        with:
          issue-number: ${{ github.event.issue.number }}
          prompt-path: .github/AutoTriage.prompt
          skip-fast-pass: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
