name: AutoTriage Backlog

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      issues:
        description: 'Space-separated issue numbers'
        required: false
      enabled:
        description: 'Enable writes (false = dry-run)'
        type: boolean
        required: false

permissions:
  contents: read
  issues: write

concurrency:
  group: autotriage-backlog
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache triage DB
        id: cache-db
        uses: actions/cache@v4
        with:
          path: triage-db.json
          key: ${{ runner.os }}-triage-db-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-triage-db-

      - name: AutoTriage (batch)
        uses: danielchalmers/AutoTriage@main
        with:
          prompt-path: .github/AutoTriage.prompt
          issue-numbers: ${{ github.event.inputs.issues }}
          db-path: triage-db.json
          enabled: ${{ github.event_name == 'workflow_dispatch' && inputs.enabled || true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: triage-artifacts-${{ github.run_number }}
          path: |
            triage-db.json
            artifacts/

