name: AutoTriage (Issues)

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AutoTriage - triage issue
        uses: danielchalmers/AutoTriage@main
        with:
          issue-number: ${{ github.event.issue.number }}
          prompt-path: .github/AutoTriage.prompt
          enabled: true
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
