name: AutoTriage (Backlog)

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      issues:
        description: 'Space-separated issue numbers'
        required: false
      dry-run:
        description: 'Dry run (true = no writes)'
        type: boolean
        required: false

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: autotriage-backlog
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache triage DB
        id: cache-db
        uses: actions/cache@v4
        with:
          path: triage-db.json
          key: ${{ runner.os }}-triage-db-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-triage-db-

      - name: AutoTriage - triage backlog
        uses: danielchalmers/AutoTriage@main
        with:
          issues: ${{ github.event.inputs.issues }}
          prompt-path: .github/AutoTriage.prompt
          dry-run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run || false }}
          db-path: triage-db.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: triage-artifacts-${{ github.run_number }}
          path: |
            triage-db.json
            artifacts/
