name: "AutoTriage"
description: "AI issue & PR triage that reads context, drafts a plan, and applies it according to your project prompt."
author: "Daniel Chalmers"
branding:
  color: "blue"
  icon: "robot"

inputs:
  additional-instructions:
    description: "Additional instructions appended to the prompt for testing or tweaking behavior without committing a new prompt."
    required: false
  budget-scale:
    description: "Scalar multiplier for internal Fast/Pro context limits. Use values >1 to allow more prompt context."
    required: false
    default: "1"
  context-caching:
    description: "Set to true to enable Gemini context caching (https://ai.google.dev/gemini-api/docs/caching), which reduces token usage when triaging multiple issues. Requires a paid Gemini plan."
    required: false
    default: "false"
  db-path:
    description: "Optional path to a JSON file that stores per-item history between runs."
    required: false
  dry-run:
    description: "Set to true to log the plan only; false applies labels, comments, and title changes."
    required: false
    default: "false"
  extended:
    description: "Set to true to include unchanged issues and recently closed issues during backlog auto-discovery."
    required: false
    default: "false"
  issues:
    description: "Space or comma separated list of issue / PR numbers to triage explicitly; when omitted the GitHub event target is used."
    required: false
  max-fast-runs:
    description: "Cap on how many targets can be analyzed with the fast model during this run."
    required: false
    default: "100"
  max-pro-runs:
    description: "Cap on how many targets can escalate to the review pass during this run."
    required: false
    default: "20"
  model-fast:
    description: "Identifier of the fast analysis model used for the first pass (default shown below). Leave blank to skip the fast pass."
    required: false
    default: "gemini-2.5-flash"
  model-pro:
    description: "Identifier of the deeper review model used when the fast pass asks for confirmation."
    required: false
    default: "gemini-3-flash-preview"
  prompt-path:
    description: "Repo-relative path to the prompt template that governs triage behavior (tone, rules, closure policy)."
    required: false
    default: ".github/AutoTriage.prompt"
  readme-path:
    description: "Path to an optional Markdown file (e.g., your README) that is bundled into the AI prompt for extra context."
    required: false
    default: "README.md"
  strict-mode:
    description: "Set to true to fail the overall job if any runs have errors."
    required: false
    default: "false"

runs:
  using: "node24"
  main: "dist/index.js"
