name: "AutoTriage"
description: "AI issue & PR triage: summarize, label, comment, retitle, and optionally close using a project prompt + Gemini."
author: "AutoTriage"
branding:
  color: "blue"
  icon: "robot"

inputs:
  issue-number:
    description: "Single issue or PR number to triage (defaults to the GitHub event context)."
    required: false
  issue-numbers:
    description: "Space or comma separated list of issue / PR numbers to triage explicitly."
    required: false
  prompt-path:
    description: "Repo-relative path to the prompt template that governs triage behavior."
    required: false
    default: ".github/AutoTriage.prompt"
  enabled:
    description: "true = apply changes; false = dry-run (log planned operations only)."
    required: false
    default: "true"
  db-path:
    description: "Optional path to JSON file storing per-issue summary + cumulative reasoning history."
    required: false
  model-fast:
    description: "Gemini model name for the first (fast / inexpensive) analysis pass."
    required: false
    default: "gemini-2.5-flash"
  model-pro:
    description: "Gemini model name for the second (higher quality) pass if needed."
    required: false
    default: "gemini-2.5-pro"
  model-temperature:
    description: "Sampling temperature (0-2). Lower = deterministic; higher = more exploratory."
    required: false
    default: "1.0"
  max-timeline-events:
    description: "Maximum most-recent timeline events included in the prompt context."
    required: false
    default: "50"
  max-operations:
    description: "Global cap on how many actions (label/comment/title/close) may execute this run."
    required: false
    default: "10"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Build
      run: npm run build
      shell: bash
    - name: Run AutoTriage
      run: node dist/index.js
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

