name: "AutoTriage"
description: "Labels, comments, edits titles, and optionally closes issues/PRs via a project prompt + Gemini."
author: "AutoTriage"
branding:
  color: "blue"
  icon: "robot"

inputs:
  issue-number:
    description: "Issue number to comment on. Defaults to the current event's issue."
    required: false
  issue-numbers:
    description: "Space- or comma-separated list of issue numbers to process."
    required: false
  prompt-path:
    description: "Path to the project prompt file (relative to repo root)."
    required: false
  default: ".github/AutoTriage.prompt"
  enabled:
    description: "If true, performs write actions (labels/comments/close). Otherwise dry-run."
    required: false
    default: "true"
  db-path:
    description: "Optional JSON file to persist per-issue summary, full reasoning history, and last triaged date."
    required: false
  model-fast:
    description: "Gemini fast model name."
    required: false
    default: "gemini-2.5-flash"
  model-pro:
    description: "Gemini pro model name."
    required: false
    default: "gemini-2.5-pro"
  model-temperature:
    description: "Generation temperature for the model (0.0–2.0 typical)."
    required: false
    default: "1.0"
  max-timeline-events:
    description: "Trim timeline to this many most recent events to control prompt size."
    required: false
    default: "50"
  max-operations:
    description: "Maximum number of operations to perform across the entire run before exiting early."
    required: false
    default: "10"

runs:
  using: "node22"
  main: "dist/index.js"

