name: "AutoTriage"
description: "AI assistant that labels issues/PRs and comments to gather info. Minimal version posts 'Test' on issues."
author: "AutoTriage"
branding:
  color: "blue"
  icon: "robot"

inputs:
  issue-number:
    description: "Issue number to comment on. Defaults to the current event's issue."
    required: false

runs:
  using: "node20"
  main: "dist/index.js"

