name: AutoTriage (Comments)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage_comment:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triage comment
        uses: ./
        with:
          issue-number: ${{ github.event.issue.number }}
          prompt-path: examples/AutoTriage.prompt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: triage-artifacts-${{ github.run_number }}
          path: |
            triage-db.json
            artifacts/
