name: AutoTriage (Issues)

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  triage_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AutoTriage - triage issue
        if: ${{ secrets.GEMINI_API_KEY != '' }}
        uses: ./
        with:
          issue-number: ${{ github.event.issue.number }}
          prompt-path: .github/scripts/AutoTriage.prompt
          enabled: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
