name: AutoTriage Example (Issues Opened)

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  comment_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AutoTriage - comment "Test"
        uses: ./
        with:
          issue-number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
