name: AutoTriage (PRs)

on:
  pull_request_target:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

jobs:
  triage_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triage PR
        if: ${{ secrets.GEMINI_API_KEY != '' }}
        uses: ./
        with:
          issue-number: ${{ github.event.pull_request.number }}
          prompt-path: examples/AutoTriage.prompt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
