name: AutoTriage (PRs)

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Triage PR
        uses: ./
        with:
          issue-number: ${{ github.event.pull_request.number }}
          prompt-path: examples/AutoTriage.prompt
          model-fast: gemini-2.5-pro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: triage-artifacts-${{ github.run_number }}
          path: |
            triage-db.json
            artifacts/
